apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: zomato
  name: zomato
  labels:
    app: zomato
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zomato
  template:
    metadata:
      labels:
        app: zomato
    spec:
      containers:
      - name: zomato
        image: kastrov/zomato:latest
        ports:
        - containerPort: 3000
