apiVersion: v1
kind: Service
metadata:
  namespace: zomato
  name: zomato
  labels:
    app: zomato
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30001
  selector:
    app: zomato
